function processForm() {
        var jobList = 
        {
        
        "LASM": {"Title": "Los Angeles Sales Manager", "Description": "<strong>Description</strong><p>There is an exciting opportunity for a seasoned sales professional to join MODA Light’s growing sales team. Local and Regional Sales Managers are the face of MODA Light and responsible for relationship management between internal resources, specifiers, customers, and agents, creating and closing opportunities, meeting sales goals, and providing industry leading customer service.</p><br><br><strong>Responsibilities</strong>  <p>Be a trusted resource for the local agent and clients, and the “expert” for all things MODA Light.</p>        <p>Develop and build relationships with agent and specifiers to better understand customer needs.</p>        <p>Promote MODA Light products to agent and clients through training and sales calls within the assigned region.</p> <p> Identify opportunities to improve the customer experience.</p> <p>Develop, implement, and update sales strategies to meet or exceed sales goals within assigned region.</p>  <p>Represent MODA Light at industry events, trade shows, seminars, etc. as required.</p>  <p>Conduct market research, provide updates and reports, and anticipated sales forecast within assigned region.</p>   <p>Evaluate and report on the competitive marketplace within assigned region.</p>  <p>Work as a liaison between the customer, production, and inside sales to ensure customer satisfaction.</p>  <br>        <strong>Requirements</strong>        <p>Bachelor’s Degree or the equivalent work-related experience in lighting sales/marketing/design field.</p> <p>5+ years’ experience in the lighting industry with proven track record of success.</p>  <p>Ability to travel occasionally.</p>  <p>Excellent verbal and written communication and presentation skills.</p>  <p>Self-directed, ability to produce results independently.</p>  <p>Solid strategic planning and execution skills.</p>  <p>Technical aptitude.</p> <p>Ability to adapt creative solutions.</p> <p>Organized and detail oriented.</p>  <p>Excellent networking skills.</p> <br><p><strong>The preferred candidate will need to reside within the Los Angeles, California metro area.</strong></p><br>   <strong>Benefits</strong>   <p>Medical, Dental, and Vision coverage offered.</p> <p>401(k)</p>  <p>PTO(Paid Time Off)</p> <br>"},
        //"NASM": {"Title": "National Accounts Sales Manager", "Description": "<strong>Responsibilities:</strong>               <p>Develop a target list of end-user accounts and strategy to penetrate each account with the assistance of the company’s sales support.</p>        <p>Focus on end-user relationships.</p>        <p>Prepare presentations to close an account with the company’s support.        </p>        <p>Maintain on-going relationships with established accounts.        </p>        <br>        <strong>Skills:</strong>        <p>Thorough understanding of LED lighting technology        </p>        <p>Professional presenter</p>        <p>Capable of multitasking with excellent time management</p>        <p>Confident in ability to close sales</p><br>"},
        "DFT": {"Title": "DMX Field Technician", "Description": "<strong>Responsibilities</strong><p>Work with our customers and sales representatives to understand the requirements of projects in order to provide the appropriate onsite commissioning and technical support to ensure all objectives are met.</p><p>Provide technical assistance to customers through commissioning and programming process.</p><p>Participate in project mock-ups onsite or in house.</p><p>Ensure technical and manufacturing coordination on large scale projects.</p><p>Provide training to agents and in house Application/Sales team.</p> <br> <strong>Skills</strong><p>Significant experience with lighting controls protocols (DMX, RDM, 0-10v, DALI).</p><p>Ability to read and navigate construction documents.</p><p>Ability to define problems, collect data, and to interpret an extensive variety of technical information with the conclusions comfortably presented to Moda Light team and customers.</p> <br> <strong>Requirements</strong><p>Bachelor’s degree (B.A.) in Lighting, Engineering, Theatre or Design preferred.</p><p>4+ years experience with lighting controls and/or building management systems design, specification and installation support.</p><br><p><strong>The preferred candidate will be needing to reside within the Las Vegas, Nevada area.</strong></p><br>"},
        "SE": {"Title": "Software Engineer", "Description": "<strong>Responsibilities</strong><p>Design and develop firmware architecture to be utilized in cutting-edge lighting fixtures.<p>Debug software/firmware using emulators and simulators.<p>Develop applications using object-oriented design and open source development.<p>Program in high level and low-level languages as appropriate including C/C++ and assembler.</p><br><strong>Requirements</strong><p>Bachelor’s degree or greater in Engineering.<p>1-2 years of professional experience directly related experience in embedded systems design and development.<p>Knowledge with C and Makefiles are required, C++ is a plus but not required.</p><p><strong>The preferred candidate will be needing to reside within the Las Vegas, Nevada area.</strong></p><br>"},
        "SEE": {"Title": "Senior Electrical Engineer", "Description": "<strong>Responsibilities</strong><br><p>Conduct research into the feasibility, design, operation and performance of electrical and electronic components, assemblies, and systems.<p>Design printed circuit board assemblies utilizing CAD software and creation of build packages for use by contract manufacturers.<p>Program devices, applications, and interfaces to support lighting controls development.<p>Source, assemble, and test product prototypes.</p><br><strong>Requirements</strong><br><p>Experience with 3D CAD software.<p>Bachelor of Science Electrical or Electronics Engineering.<p>3+ years electronic product design.<br><p><strong>The preferred candidate will be needing to reside within the Las Vegas, Nevada area.</strong></p><br>"},
        //"WM": {"Title": "Warehouse Manager", "Description": "<strong>Responsibilities:</strong><br><p>Plan, coordinate, and schedule assignments and ensures the efficiency of warehouse operations.</p><p>Accurately receive, store and distribute warehouse items according to company standards.</p><p>Record amounts of materials or items received or distributed.</p><p>Ensure warehouse is organized, accessible and safe at all times.</p><p>Read work orders, shipping orders, or requisitions to determine items to be moved, gathered, or distributed and/or shipped.</p><br><strong>Requirements:</strong><p>3 years experience in warehousing, receiving, inventory control or material management.</p><br>"},
        "PRM": {"Title": "Production Manager", "Description": "<strong>Responsibilities</strong><br><p>Identify market needs for new products and existing product improvements by obtaining industry and technology intel and overseeing involvement of Marketing and Sales resources.</p><p>Forecast Sales and determine pricing of new products from the design specifications phase to IOQ phase by working with Marketing and Sales to secure their buy in and commitment to product specs, pricing, and sales volume.</p><p>Analyzes ROI and make recommendations on products worth moving forward.</p><p>Present team’s product designs and specifications for Executive approval.</p><p>Oversee product lifecycle, SKUs, and documentation to effectively support business needs and enhance efficiencies.</p><p>Work with engineering teams in the US and Taiwan to develop new product proposals including design sketches, design engineering, line drawings, and new technology recommendations.</p><br><strong>Requirements</strong><p> 3 years experience in production management.</p><br><p><strong>The preferred candidate will be needing to reside within the Las Vegas, Nevada area.</strong></p><br>"},
        "AE": {"Title": "Application Engineer", "Description": "<strong>Responsibilities</strong><br><p>Transform handwritten sketches and field measurements into CAD format.</p><p>Receive custom quote requests from the sales department and allocate to the proper party.</p><p>Review and edit potential quotes from team members.</p><br><strong>Requirements</strong> <p>Strong understanding of 3D modeling.</p><p>Ability to read and interpret plans and specifications, make accurate architectural drawings and tracings, prepare lists of materials from architectural plans, detect errors and discrepancies in plans and specifications, organize data and prepare reports and specifications in clear and concise form.</p><p>Use CAD software for architectural design and drafting.</p><br><p><strong>The preferred candidate will be needing to reside within the Las Vegas, Nevada area.</strong></p><br>"},
        //"RGC": {"Title": "Regional Sale - Canada", "Description": "<p>The Regional Sales Manager will be responsible for executing strategies that maximize profit and support our inside sales and marketing goals.</p><p>Perform face-to-face sales conferences as well as manage relationships between our representative agencies.</p><p>Increase awareness, appreciation, and understanding of the Moda Light brand.</p><br><strong>Responsibilities:</strong><br><p>Traveling is expected to be 50-70% of the job.</p><p>Target, establish, and nurture relationships with external rep agents, specifiers, distributors, and contractors.</p><p>Develop and execute local and regional sales and marketing initiatives that advance our corporate sales and marketing goals.</p><p>Understand the internal business processes of our rep agency partners and co-develop a tailored strategy to increase market share within the territories they serve.</p><p>Coordinate with other internal teams, departments, and individuals to ensure a high degree of customer satisfaction.</p><p>Planning for and managing all sales promotion activities within the region, including trade shows, seminars, training classes, and customer-driven activities.</p><br><strong>Skills:</strong><p>Ability to learn and adapt quickly.</p><p>Capable of working both independently and collaboratively.</p><p>Experience with customer relationship management software.</p><br><strong>Requirements:</strong><p>Thorough understanding of LED lighting technology.</p><p>Minimum of 3 years outside sales experience required.</p><p>Lighting design and installation experience preferred.</p><br>"},
        }


        var parameters = location.search.substring(1).split("&");
        var temp = parameters[0].split("=");
        l = unescape(temp[1]);
        
        var title = jobList[l]["Title"];
        var description = jobList[l]["Description"];
        document.getElementById("title").innerHTML = title;
        document.getElementById("description").innerHTML = description;
        
//        window.history.pushState(pushObj, "Jobs", "");
}
processForm();



//      This is to test url manual refresh function

function processAjaxData(response, urlPath){
        document.getElementById("content").innerHTML = response.html;
        document.title = response.pageTitle;
        window.history.pushState({"html":response.html, "pageTitle":response.pageTitle}, "", urlPath);
}

window.onpopstate = function(e){
        if(e.state){
                document.getElementById("content").innerHTML = e.state.html;
                document.title = e.state.pageTitle;
        }
}
clearCache;