function processForm() {
        var jobList = 
        {
        

        //"AE": {"Title": "Application Engineer", "jobDate": "August 31st, 2020", "jobLoc": "Las Vegas, Nevada, USA", "Description": "<strong>Responsibilities</strong>    <p>&#8226; Transform handwritten sketches and field measurements into CAD format.</p>  <p>&#8226; Receive custom quote requests from the sales department and allocate to the proper party.</p>        <p>&#8226; Review and edit potential quotes from team members.</p>      <br><strong>Requirements</strong> <p>&#8226; Strong understanding of 3D modeling.</p>   <p>&#8226; Ability to read and interpret plans and specifications, make accurate architectural drawings and tracings, prepare lists of materials from architectural plans, detect errors and discrepancies in plans and specifications, organize data and prepare reports and specifications in clear and concise form.</p>     <p>&#8226; Use CAD software for architectural design and drafting.</p>  <br><p><strong>The preferred candidate will be needing to reside within the Las Vegas, Nevada area.</strong></p><br>"},
        //"RGC": {"Title": "Regional Sale - Canada", "Description": "<p>The Regional Sales Manager will be responsible for executing strategies that maximize profit and support our inside sales and marketing goals.</p><p>Perform face-to-face sales conferences as well as manage relationships between our representative agencies.</p><p>Increase awareness, appreciation, and understanding of the Moda Light brand.</p><br><strong>Responsibilities:</strong><br><p>Traveling is expected to be 50-70% of the job.</p><p>Target, establish, and nurture relationships with external rep agents, specifiers, distributors, and contractors.</p><p>Develop and execute local and regional sales and marketing initiatives that advance our corporate sales and marketing goals.</p><p>Understand the internal business processes of our rep agency partners and co-develop a tailored strategy to increase market share within the territories they serve.</p><p>Coordinate with other internal teams, departments, and individuals to ensure a high degree of customer satisfaction.</p><p>Planning for and managing all sales promotion activities within the region, including trade shows, seminars, training classes, and customer-driven activities.</p><br><strong>Skills:</strong><p>Ability to learn and adapt quickly.</p><p>Capable of working both independently and collaboratively.</p><p>Experience with customer relationship management software.</p><br><strong>Requirements:</strong><p>Thorough understanding of LED lighting technology.</p><p>Minimum of 3 years outside sales experience required.</p><p>Lighting design and installation experience preferred.</p><br>"},
        //"APAR": {"Title": "Accounts Receivable/Payable Billing Clerk", "jobDate": "March 11th, 2021", "jobLoc": "Las Vegas, Nevada, USA", "Description": "<p>We are looking for a detail-oriented, reliable Accounts Receivable/Payable Billing Clerk to correspond with customers regarding payments, issue invoices, and pays invoices by verifying and completing payable and receivable transactions. You should be able to multitask and be able to deal with customer concerns in a professional manner.</p><br><p>The potential candidate should have a good grasp of accounting practices and strong organizational skills. An outstanding candidate will demonstrate excellent communication skills and a knack for working with numbers.</p><br><strong>Responsibilities</strong><br><p>&#8226; Prepares work to be accomplished by gathering and sorting documents and related information.</p><p>&#8226; Creating and issuing invoices to customers.</p><p>&#8226; Processing credit memos.</p><p>&#8226; Following up on outstanding payments and answering customer queries.</p><p>&#8226; Monitoring all customer payments and preparing monthly billing reports.</p><p>&#8226; Updating accounting records with issued invoices, processed payments, new balances, and customer contact information.</p><p>&#8226; Pays invoices by verifying transaction information; scheduling and preparing disbursements; obtaining authorization of payment.</p><p>&#8226; Obtains revenue by verifying transaction information; computing charges and refunds; preparing and mailing invoices; identifying delinquent accounts and insufficient payments.</p><p>&#8226; Collects revenue by reminding delinquent accounts, notifying customers of insufficient payments.</p><p>&#8226; Maintains accounting ledgers by posting account transactions.</p><p>&#8226; Resolves account discrepancies by investigating documentation, payments, or adjustments.</p><p>&#8226; Maintains financial security by following internal accounting controls.</p> <p>&#8226; Secures financial information by completing data base backups.</p><p>&#8226; Maintains financial historical records by filing accounting documents.</p><p>&#8226; Contributes to team effort by accomplishing related results as needed.</p>     <br><strong>Skills &amp; Qualifications</strong><p>&#8226; High School Diploma/GED.</p><p>&#8226; Previous experience as an accounts receivable/payable billing clerk or in similar role.</p><p>&#8226; Knowledge of accounting software such as NetSuite.</p><p>&#8226; Working knowledge of accounting standards and regulations.</p> <p>&#8226; Strong communication, organizational and time-management skills.</p> <p>&#8226; Ability to work efficiently under pressure.</p> <p>&#8226; Proficient in Microsoft Office.</p> <p>&#8226; Excellent Math Skills.</p> <p>&#8226; Strong attention to detail.</p><br><br><p>Office hours are form 7:30am - 4:00pm, Monday thru Friday.<br>Competitive employee benefits package is provided after probationary period.</p><br>"},
        //"GD": {"Title": "Graphic Designer - Technical", "jobDate": "March 16th, 2021", "jobLoc": "Las Vegas, Nevada, USA", "Description": "<p>MODA Light is an innovative architectural lighting company and is currently seeking a Graphic Designer to join its team. This position collaborates with members of, product development, engineering and senior leadership to design compliant, compelling, clear and concise technical documents such as specification sheets, product guides and installation instructions. Strong candidates will have a positive attitude, strong work ethic, and excellent communication skills both written and verbally.</p><br><strong>Qualifications &amp; Skills</strong><br><p>&#8226; Proficient with programs in Adobe Creative Suite (Illustrator, Photoshop, InDesign, Lightroom)</p><p>&#8226; Proficiency in Cinema 4D, BarTender or other related software a plus</p><p>&#8226; Possess a high level of precision, dexterity, and attention to detail</p><p>&#8226; Strong graphic design, layout, and analytical skills</p><p>&#8226; Strong presentation, verbal, visual and written communication skills</p><p>&#8226; Ability to work independently and deadline-oriented</p><p>&#8226; Knowledgeable in desktop publishing tools and graphic design software</p><p>&#8226; Handles constructive criticism well</p><p>&#8226; Time-management skills</p><p>&#8226; Acute vision</p>  <br><strong>Education &amp; Experience Requirements</strong><p>&#8226; Bachelor's degree in Art, Graphic Design, Industrial Design, or a related field</p><p>&#8226; 3 - 5 years of experience in graphic design or related field</p><p>&#8226; Portfolio &amp; Samples Work if available</p><p>&#8226; Intermediate proficiency with HTML, CSS &amp; JavaScript a strong plus</p>  <br><br><p>Office hours are form 7:30am - 4:00pm, Monday thru Friday.</p><br>"},
        "TSM": {"Title": "Technical Services Manager", "jobDate": "April 14th, 2021", "jobLoc": "Las Vegas, Nevada, USA", "Description": "<p>MODA Light is an innovative architectural lighting company and is currently seeking a Technical Services Manager to join its team. The primary responsibility of this position is to provide the highest quality of customer service and technical support to our business units, sales teams, agent partners, customers and is responsible for responding to customer (internal and external) requests regarding techincal questions. Strong candidates will have a positive attitude and the ability to lead an effective team.</p><br><strong>Qualifications &amp; Skills</strong><br><p>&#8226; Maintain expert level of product knowledge and application.</p><p>&#8226; Provide design and specification development support to sales teams, agents, consultants, specifiers, and distributors including advising customer on correct product to purchase based on their application.</p><p>&#8226; Troubleshoot field problems reported by Inside Sales, Agents, Distributors, Contractors, and/or End users of product.</p><p>&#8226; Work with our customers and sales representatives to udnerstand the requirements of DMX projects to provide the appropriate commissioning and programming process.</p><p>&#8226; Facilitate samples/mock-ups onsite or in-house.</p><p>&#8226; Ensure techinical and manufacturing coordination on large scale projects.</p><p>&#8226; Provide training to Agents and in-house Application/Sales team.</p><p>&#8226; Oversee the entire customer service technical support process and make adjustments/improvements to the process, to better support the company's customers.</p><p>&#8226; Support internal Quality Control and RMA processes.</p><p>&#8226; Prepare deliverables that include data collection, gap analyses, forecasting analyses, presentation, written reports, and recommendations.</p>  <br><strong>Education &amp; Experience Requirements</strong><p>&#8226; Bachelor's degree (B.A.) in Lighting, Enginerring, Electronics or Computer Science.</p><p>&#8226; 5+ years of experience with lighting controls and/or building management systems design, specification, and installation support.</p><p>&#8226; Significant experience with lighting control protocols (DMX, RDM, 0-10V, DALI).</p><p>&#8226; 3 - 5 years' experience managing a team.</p> <p>&#8226; Position may require occasional travel to job sites to provide technical support.</p> <br><br><p>Office hours are from 7:30am - 4:00pm, Monday thru Friday.</p><br>"},
        "MM": {"Title": "Marketing Manager", "jobDate": "June 9th, 2021", "jobLoc": "Las Vegas, Nevada, USA", "Description": "<p>MODA Light is an innovative architectural lighting company and is currently seeking a Marketing Manager to join its team. The primary responsibility of this position is to represent MODA’s brand and products in the highest regard to our customers, agents, specifiers, and partners.</p><p> The Marketing Manager will lead MODA’s marketing and branding efforts. Knowledge of the lighting industries various sales and marketing channels and experience in product marketing is essential.</p><p>Strong candidates will have a positive attitude and the ability to lead an effective team.</p><br><strong>Qualifications &amp; Skills</strong><br><p>&#8226; Partner with senior leadership to craft MODA’s brand identity, value proposition, and voice.</p><p> - Cultivate brand story and develop creative standards.</p><p> - Communicate the value proposition of MODA Products.</p><p> - Ensure that all advertising and collateral material align with brand design.</p><p>&#8226; Management of all marketing assets including digital, website, catalog/print.</p><p>&#8226; Develop and execute website strategy including major overhaul and/or complete rebuild.</p><p>&#8226; Create marketing strategy for new product launches and oversee creation of all product related collateral.</p><p>&#8226; Responsible for digital marketing strategy, including website and social media, and content management.</p><p>&#8226; Collaborate with marketing and sales teams to ensure an effective social media strategy, email marketing strategy, and calendar planning.</p><p>&#8226; Develop Marketing Plan and manage execution of marketing materials and programs.</p><p>&#8226; Analyze data to track effectiveness of strategy and identify new opportunities or strategies.</p><p>&#8226; Oversee marketing for conferences, trade shows, and major events.</p><p>&#8226; Work with Inside Sales and Customer Service team to increase overall product utilization by developing strategic marketing plans throughout product life cycle.</p><p>&#8226; Work with the product development team to ensure we are staying on top of latest marketing trends.</p><p>&#8226; Make necessary updates to MODA’s website, as needed.</p><p>&#8226; Create and maintain SOPs for various marketing processes.</p><p>&#8226; Completes additional marketing tasks as assigned by senior leadership.</p>  <br><strong>Education &amp; Experience Requirements</strong><p>&#8226; Bachelor's degree (B.A.) in Business or Marketing preferred.</p><p>&#8226; 5+ years Marketing Experience</p><p>&#8226; 3 - 5 years' experience managing a team.</p><p>&#8226; Lighting industry experience preferred.</p><p>&#8226; Proficiency with digital marketing forums such as social media and content marketing.</p> <br><br><p>Must be available to work Monday-Friday, 7:30am - 4pm.</p><br>"},
        }


        var parameters = location.search.substring(1).split("&");
        var temp = parameters[0].split("=");
        l = unescape(temp[1]);
        
        var title = jobList[l]["Title"];
        var description = jobList[l]["Description"];
        var jobDate = jobList[l]["jobDate"];
        var jobLoc = jobList[l]["jobLoc"];

        document.getElementById("title").innerHTML = title;
        document.getElementById("description").innerHTML = description;
        document.getElementById("jobDate").innerHTML = jobDate;
        document.getElementById("jobLoc").innerHTML = jobLoc;
        
}
processForm();

clearCache;
